### ISSUE TITLE
Repack text_assets_global.str

### ISSUE THREAD

**Issue by romhackingvn** [tgp1994/Gibbed.Visceral#1]
I have a problem with strpack tool, could you help me fix that! Thanks! It contain over 500 files
! Thanks!
[untitled](https://user-images.githubusercontent.com/12272584/28006943-b50371de-657b-11e7-824a-cfd708a88330.png)

[text_assets_global.zip](https://github.com/tgp1994/Gibbed.Visceral/files/1134670/text_assets_global.zip)

**Comment by tgp1994** [comment]
Hi @romhackingvn,

I haven't worked on this in a long time... You might have more luck creating an issue at the original project, found [here](https://github.com/gibbed/Gibbed.Visceral). I'll leave this open in case I come back to this project in the future.

**Comment by romhackingvn** [comment]
Thanks! I only need repack this file @@!

2017-07-12 1:06 GMT+07:00 Glen <notifications@github.com>:

**Comment by tgp1994** [comment]
Hey @romhackingvn , I noticed Rick already had his StrPack program on github (https://github.com/gibbed/Gibbed.Visceral), I think I'll delete this repository to prevent confusion and reduce redundancy a little. If you want to open a ticket there, I'll check it out and see if I can help you.
